using Baci.ArcGIS.Geoprocessor.Models;
using Baci.ArcGIS.Geoprocessor.Models.Attributes;
using Baci.ArcGIS.Geoprocessor.Models.Attributes.Domains;
using Baci.ArcGIS.Geoprocessor.Models.Attributes.DataTypes;
using Baci.ArcGIS.Geoprocessor.Models.Enums;
using System.Collections.Generic;
using System.ComponentModel;
using System;

namespace Baci.ArcGIS.Geoprocessor.CrimeAnalysisandSafetyTools
{
	/// <summary>
	/// <para>Cell Phone Records To Feature Class</para>
	/// <para>Imports cell phone records from wireless network providers and associates those records with a cell site and sector feature classes as generated by the Cell Site Records To Feature Class tool based on identifier fields.</para>
	/// </summary>
	public class CellPhoneRecordsToFeatureClass : AbstractGPProcess
	{
		/// <summary>
		/// <para>Constructor that takes all required parameters for geoprocessor execution.</para>
		/// </summary>
		/// <param name="InTable">
		/// <para>Input Phone Records Table</para>
		/// <para>The input table containing call records or phone data event records provided by the wireless network provider.</para>
		/// </param>
		/// <param name="InSiteFeatures">
		/// <para>Input Cell Site Points</para>
		/// <para>The feature class containing cell site points generated by the Cell Site Records to Feature Class tool.</para>
		/// </param>
		/// <param name="InSectorFeatures">
		/// <para>Input Cell Site Sectors</para>
		/// <para>The feature class containing cell site sectors generated by the Cell Site Records to Feature Class tool.</para>
		/// </param>
		/// <param name="OutSiteFeatureClass">
		/// <para>Output Phone Record Site Points</para>
		/// <para>The point feature class containing phone record site points.</para>
		/// <para>One point will be generated per phone record linked to cell site points.</para>
		/// </param>
		/// <param name="OutSectorFeatureClass">
		/// <para>Output Phone Record Sectors</para>
		/// <para>The polygon feature class containing phone record sectors.</para>
		/// <para>One sector polygon will be generated per phone record linked to cell site sectors.</para>
		/// </param>
		/// <param name="IdFields">
		/// <para>Cell Sector ID Fields</para>
		/// <para>Specifies the unique ID field type and the fields that will be added to the output feature.</para>
		/// <para>Use the Unique ID type when the Input Phone Records Table parameter value has a unique identifier for all cell sector antennas. Use a combination of other ID Type values when the Input Phone Records Table parameter value does not contain a universal unique identifier for all cell sector antennas.</para>
		/// <para><para/></para>
		/// <para>ID Type—The field name to be included in the output feature classes.</para>
		/// <para>Field—The name of the fields that uniquely identify the cell sector antennas. These will be added to the output feature class.</para>
		/// <para>ID Type options are as follows:</para>
		/// <para>Unique ID—Uniquely identifies a cell sector antenna</para>
		/// <para>Site ID—Uniquely identifies a cell site</para>
		/// <para>Sector ID—Uniquely identifies a cell sector</para>
		/// <para>Switch ID—Uniquely identifies a wireless network switch</para>
		/// <para>LAC ID—Uniquely identifies the Location Area Code</para>
		/// <para>Cascade ID—Uniquely identifies the sector in the wireless network cascade</para>
		/// <para>Cell ID—Identifies the sector within an Location Area Code</para>
		/// </param>
		/// <param name="SubscriberField">
		/// <para>Subscriber ID Field</para>
		/// <para>The field in the input table that contains the phone number or identifier of the subscriber.</para>
		/// </param>
		public CellPhoneRecordsToFeatureClass(object InTable, object InSiteFeatures, object InSectorFeatures, object OutSiteFeatureClass, object OutSectorFeatureClass, object IdFields, object SubscriberField)
		{
			this.InTable = InTable;
			this.InSiteFeatures = InSiteFeatures;
			this.InSectorFeatures = InSectorFeatures;
			this.OutSiteFeatureClass = OutSiteFeatureClass;
			this.OutSectorFeatureClass = OutSectorFeatureClass;
			this.IdFields = IdFields;
			this.SubscriberField = SubscriberField;
		}

		/// <summary>
		/// <para>Tool Display Name : Cell Phone Records To Feature Class</para>
		/// </summary>
		public override string DisplayName => "Cell Phone Records To Feature Class";

		/// <summary>
		/// <para>Tool Name : CellPhoneRecordsToFeatureClass</para>
		/// </summary>
		public override string ToolName => "CellPhoneRecordsToFeatureClass";

		/// <summary>
		/// <para>Tool Excute Name : ca.CellPhoneRecordsToFeatureClass</para>
		/// </summary>
		public override string ExcuteName => "ca.CellPhoneRecordsToFeatureClass";

		/// <summary>
		/// <para>Toolbox Display Name : Crime Analysis and Safety Tools</para>
		/// </summary>
		public override string ToolboxDisplayName => "Crime Analysis and Safety Tools";

		/// <summary>
		/// <para>Toolbox Alise : ca</para>
		/// </summary>
		public override string ToolboxAlise => "ca";

		/// <summary>
		/// <para>Valid Environment Params</para>
		/// </summary>
		public override string[] ValidEnvironments => new string[] { "MDomain", "MResolution", "MTolerance", "XYDomain", "XYResolution", "XYTolerance", "ZDomain", "ZResolution", "ZTolerance", "autoCommit", "configKeyword", "extent", "geographicTransformations", "maintainAttachments", "outputMFlag", "outputZFlag", "outputZValue", "qualifiedFieldNames", "scratchWorkspace", "workspace" };

		/// <summary>
		/// <para>Tool Parametrs</para>
		/// </summary>
		public override object[] Parameters => new object[] { InTable, InSiteFeatures, InSectorFeatures, OutSiteFeatureClass, OutSectorFeatureClass, IdFields, SubscriberField, DestinationField!, AdditionalIdFields!, StartTimeField!, DurationField!, EndTimeField!, ConvertUtc!, LocationXField!, LocationYField!, LocationCoordinateSystem!, OutCallPoints! };

		/// <summary>
		/// <para>Input Phone Records Table</para>
		/// <para>The input table containing call records or phone data event records provided by the wireless network provider.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.must)]
		[GPTableView()]
		public object InTable { get; set; }

		/// <summary>
		/// <para>Input Cell Site Points</para>
		/// <para>The feature class containing cell site points generated by the Cell Site Records to Feature Class tool.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.must)]
		[GPFeatureLayer()]
		[GPFeatureClassDomain()]
		public object InSiteFeatures { get; set; }

		/// <summary>
		/// <para>Input Cell Site Sectors</para>
		/// <para>The feature class containing cell site sectors generated by the Cell Site Records to Feature Class tool.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.must)]
		[GPFeatureLayer()]
		[GPFeatureClassDomain()]
		public object InSectorFeatures { get; set; }

		/// <summary>
		/// <para>Output Phone Record Site Points</para>
		/// <para>The point feature class containing phone record site points.</para>
		/// <para>One point will be generated per phone record linked to cell site points.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.must)]
		[DEFeatureClass()]
		public object OutSiteFeatureClass { get; set; }

		/// <summary>
		/// <para>Output Phone Record Sectors</para>
		/// <para>The polygon feature class containing phone record sectors.</para>
		/// <para>One sector polygon will be generated per phone record linked to cell site sectors.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.must)]
		[DEFeatureClass()]
		public object OutSectorFeatureClass { get; set; }

		/// <summary>
		/// <para>Cell Sector ID Fields</para>
		/// <para>Specifies the unique ID field type and the fields that will be added to the output feature.</para>
		/// <para>Use the Unique ID type when the Input Phone Records Table parameter value has a unique identifier for all cell sector antennas. Use a combination of other ID Type values when the Input Phone Records Table parameter value does not contain a universal unique identifier for all cell sector antennas.</para>
		/// <para><para/></para>
		/// <para>ID Type—The field name to be included in the output feature classes.</para>
		/// <para>Field—The name of the fields that uniquely identify the cell sector antennas. These will be added to the output feature class.</para>
		/// <para>ID Type options are as follows:</para>
		/// <para>Unique ID—Uniquely identifies a cell sector antenna</para>
		/// <para>Site ID—Uniquely identifies a cell site</para>
		/// <para>Sector ID—Uniquely identifies a cell sector</para>
		/// <para>Switch ID—Uniquely identifies a wireless network switch</para>
		/// <para>LAC ID—Uniquely identifies the Location Area Code</para>
		/// <para>Cascade ID—Uniquely identifies the sector in the wireless network cascade</para>
		/// <para>Cell ID—Identifies the sector within an Location Area Code</para>
		/// </summary>
		[ParamType(ParamTypeEnum.must)]
		[GPValueTable()]
		[GPCompositeDomain()]
		public object IdFields { get; set; }

		/// <summary>
		/// <para>Subscriber ID Field</para>
		/// <para>The field in the input table that contains the phone number or identifier of the subscriber.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.must)]
		[Field()]
		[GPFieldDomain()]
		public object SubscriberField { get; set; }

		/// <summary>
		/// <para>Destination Phone Number Field</para>
		/// <para>The field in the input table that contains the phone number or identifier of the callee.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.optional)]
		[Field()]
		[GPFieldDomain()]
		public object? DestinationField { get; set; }

		/// <summary>
		/// <para>Additional Cell Sector ID Fields</para>
		/// <para>Specifies the additional unique ID field type and the fields that will be added to the output feature.</para>
		/// <para>Use the Unique ID type when the Input Phone Records Table parameter value has a unique identifier for all cell sector antennas. Use a combination of other ID Type values when the Input Phone Records Table parameter value does not contain a universal unique identifier for all cell sector antennas.</para>
		/// <para>ID Type—The field name to be included in the output feature classes.</para>
		/// <para>Field—The name of the fields that uniquely identify the cell sector antennas. These will be added to the output feature class.</para>
		/// <para>ID Type options are as follows:</para>
		/// <para>Unique ID—Uniquely identifies a cell sector antenna</para>
		/// <para>Site ID—Uniquely identifies a cell site</para>
		/// <para>Sector ID—Uniquely identifies a cell sector</para>
		/// <para>Switch ID—Uniquely identifies a wireless network switch</para>
		/// <para>LAC ID—Uniquely identifies the Location Area Code</para>
		/// <para>Cascade ID—Uniquely identifies the sector in the wireless network cascade</para>
		/// <para>Cell ID—Identifies the sector within an Location Area Code</para>
		/// </summary>
		[ParamType(ParamTypeEnum.optional)]
		[GPValueTable()]
		[GPCompositeDomain()]
		public object? AdditionalIdFields { get; set; }

		/// <summary>
		/// <para>Start Date and Time Field</para>
		/// <para>The field in the input table that contains the start date and time field of the phone call or data event.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.optional)]
		[Field()]
		[GPFieldDomain()]
		[Category("Call Duration Information")]
		public object? StartTimeField { get; set; }

		/// <summary>
		/// <para>Duration Field</para>
		/// <para>The field in the input table that contains the duration of the phone call in seconds.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.optional)]
		[Field()]
		[GPFieldDomain()]
		[Category("Call Duration Information")]
		public object? DurationField { get; set; }

		/// <summary>
		/// <para>End Date and Time Field</para>
		/// <para>The field in the input table that contains the end date and time of the phone call or data event.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.optional)]
		[Field()]
		[GPFieldDomain()]
		[Category("Call Duration Information")]
		public object? EndTimeField { get; set; }

		/// <summary>
		/// <para>Convert UTC Dates to Local Time Zone</para>
		/// <para>Specifies whether the start and end date and time of the input records will be converted to the time zone of the local system or will remain in coordinated universal time (UTC).</para>
		/// <para>Checked—The start and end date and time of the input records will be converted from UTC to the time zone of the local system.</para>
		/// <para>Unchecked—The start and end date and time will not be converted. This is the default.</para>
		/// <para><see cref="ConvertUtcEnum"/></para>
		/// </summary>
		[ParamType(ParamTypeEnum.optional)]
		[GPBoolean()]
		[GPCodedValueDomain()]
		[Category("Call Duration Information")]
		public object? ConvertUtc { get; set; } = "false";

		/// <summary>
		/// <para>Estimated Phone Location X Field</para>
		/// <para>The field in the input table that contains the x-coordinate of the estimated phone location as provided by the wireless network provider.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.optional)]
		[Field()]
		[GPFieldDomain()]
		[Category("Estimated Phone Location Output Options")]
		public object? LocationXField { get; set; }

		/// <summary>
		/// <para>Estimated Phone Location Y Field</para>
		/// <para>The field in the input table that contains the y-coordinate of the estimated phone location as provided by the wireless network provider.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.optional)]
		[Field()]
		[GPFieldDomain()]
		[Category("Estimated Phone Location Output Options")]
		public object? LocationYField { get; set; }

		/// <summary>
		/// <para>Estimated Phone Location Coordinate System</para>
		/// <para>The estimated phone location coordinate system of the x,y-coordinates. The default coordinate system is WGS84.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.optional)]
		[GPCoordinateSystem()]
		[Category("Estimated Phone Location Output Options")]
		public object? LocationCoordinateSystem { get; set; } = "GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]";

		/// <summary>
		/// <para>Output Estimated Call Points</para>
		/// <para>The point feature class containing the estimated call locations as provided by the wireless network provider.</para>
		/// </summary>
		[ParamType(ParamTypeEnum.optional)]
		[DEFeatureClass()]
		[Category("Estimated Phone Location Output Options")]
		public object? OutCallPoints { get; set; }

		/// <summary>
		/// <para>Only Set The Valid Environment For This Tool</para>
		/// </summary>
		public CellPhoneRecordsToFeatureClass SetEnviroment(object? MDomain = null , double? MResolution = null , double? MTolerance = null , object? XYDomain = null , object? XYResolution = null , object? XYTolerance = null , object? ZDomain = null , object? ZResolution = null , object? ZTolerance = null , int? autoCommit = null , object? configKeyword = null , object? extent = null , object? geographicTransformations = null , bool? maintainAttachments = null , object? outputMFlag = null , object? outputZFlag = null , double? outputZValue = null , bool? qualifiedFieldNames = null , object? scratchWorkspace = null , object? workspace = null )
		{
			base.SetEnv(MDomain: MDomain, MResolution: MResolution, MTolerance: MTolerance, XYDomain: XYDomain, XYResolution: XYResolution, XYTolerance: XYTolerance, ZDomain: ZDomain, ZResolution: ZResolution, ZTolerance: ZTolerance, autoCommit: autoCommit, configKeyword: configKeyword, extent: extent, geographicTransformations: geographicTransformations, maintainAttachments: maintainAttachments, outputMFlag: outputMFlag, outputZFlag: outputZFlag, outputZValue: outputZValue, qualifiedFieldNames: qualifiedFieldNames, scratchWorkspace: scratchWorkspace, workspace: workspace);
			return this;
		}

		#region InnerClass

		/// <summary>
		/// <para>Convert UTC Dates to Local Time Zone</para>
		/// </summary>
		public enum ConvertUtcEnum 
		{
			/// <summary>
			/// <para>Checked—The start and end date and time of the input records will be converted from UTC to the time zone of the local system.</para>
			/// </summary>
			[GPValue("true")]
			[Description("CONVERT")]
			CONVERT,

			/// <summary>
			/// <para>Unchecked—The start and end date and time will not be converted. This is the default.</para>
			/// </summary>
			[GPValue("false")]
			[Description("NO_CONVERT")]
			NO_CONVERT,

		}

#endregion
	}
}
